[package]
name = "portus-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
portus-protocol = { path = "../portus-protocol" }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
