[package]
name = "portus-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
clap = { workspace = true }
portus-client = { path = "../portus-client" }
portus-protected-api = { path = "../portus-protected-api" }
portus-protocol = { path = "../portus-protocol" }
serde_json = { workspace = true }

[lints]
workspace = true
