# SPDX-License-Identifier: CC0-1.0
---
initdDir: /etc/init.d
runlevelsDir: /etc/runlevels
services:
  - { name: dbus, runlevel: default, mandatory: true }
  - { name: elogind, runlevel: default, mandatory: true }
  - { name: NetworkManager, runlevel: default, mandatory: true }
  - { name: sshd, runlevel: default, mandatory: true }
  - { name: nftables, runlevel: default, mandatory: true }
  - { name: chrony, runlevel: default, mandatory: true }
  - { name: syslog-ng, runlevel: default, mandatory: true }
disable: []
